In [2]:
import numpy as np


In [3]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [4]:
arr = np.ndarray((2, 3), dtype=int)
print(arr)


[[            0          2096             0]
 [1976562660144             0         65793]]
